import:
  - ~/.opacity.yml
env:
  TERM: xterm-256color
window:
  title: terminal
  decorations: buttonless
  padding:
    x: 12
    y: 12
font:
  normal:
    family: JetBrains Mono NL
    style: Regular
  bold:
    family: JetBrains Mono NL
    style: Bold
  italic:
    family: JetBrains Mono NL
    style: Italic
  bold_italic:
    family: JetBrains Mono NL
    style: Bold Italic
  size: 13
bell:
  enabled: false
cursor:
  thickness: 0.25
mouse:
  hide_when_typing: true
colors:
  primary:
    background: '#191919'
    foreground: '#e8e8dc'
  normal:
    #black:   '#1a191a'
    red: '#cd8155'
    green: '#bcc48c'
    yellow: '#cdb67f'
    blue: '#55585b'
    magenta: '#bcc48c'
    cyan: '#899496'
    white: '#e1e1e0'
  bright:
    #black:   '#545454'
    red: '#e58f5e'
    green: '#d5dd9d'
    yellow: '#e8cd8f'
    blue: '#6d7175'
    magenta: '#d5dd9d'
    cyan: '#9ba8aa'
    white: '#e6e6e6'
