window:
  title: terminal
  decorations: buttonless
  padding:
    x: 8
    y: 8

background_opacity: 0.8

font:
  normal:
    family: Menlo
    style: Regular
  bold:
    family: Menlo
    style: Bold
  italic:
    family: Menlo
    style: Italic
  bold_italic:
    family: Menlo
    style: Bold Italic
  size: 15

cursor:
  style:
    shape: underline
  vi_mode_style: block
  thickness: 0.25

mouse:
  hide_when_typing: true

